### ISSUE TITLE
(docs) "Advanced walkthrough" missing

### ISSUE THREAD

**Issue by BrainCrumbz** [lilasquared/NRedux#1]
Hi there

while going through the readme, it seems the anchor for "advanced walktrough" is broken. The mentioned paragraph can be found in [Handling Actions](https://github.com/lilasquared/NRedux#handling-actions) section.

Where can we find this doc?

Thanks!

**Comment by lilasquared** [comment]
I don’t think I ever finished the docs for that. I tried to mimic the docs from redux a little bit so you might be able to look at their advanced sections and get some ideas. What are you trying to do maybe I can whip up some docs quickly

**Comment by BrainCrumbz** [comment]
Thanks for the quick reply. 

> ... maybe I can whip up some docs quickly

Thanks for offering, but don't worry too much about it. We were reading about existing .NET Redux implementations, having already worked with it in Angular. 

It seems there's nothing really alive and maintained, judging by the last commit dates and issues discussion on a number of GH projects (including Redux.NET). Or are we missing something?

**Comment by lilasquared** [comment]
I’d say you’re probably right. The redux source code is however pretty small, only a few files.  This repo was basically a test to see if I could recreate the js code almost line for line. I work mainly server side with .NET and not much use for a redux there. I use MediatR which I like a lot to disconnect actions from action handlers. It supports a middleware of sorts and is also very lightweight.

**Comment by BrainCrumbz** [comment]
yep, on the server side we go with Commands and Queries as well. Most of the times manually tying API controller actions to their dedicate handler, but surely MediatR is in our radar. At some point we also used a command-based approach in a console app, given the similarity w.r.t. an API controller when you think about it.

Best regards
